project 'TomatoRun.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TomatoRun' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TomatoRun
  pod 'Google-Mobile-Ads-SDK'

  target 'TomatoRunTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
